import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbaar from '@/Components/Navbar'
import { FloatingNav } from "@/Components/ui/floating-navbar";
import { FloatingNavbar } from "@/Components/FloatingNavbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        

        {/* <Navbaar/> */}
        <FloatingNavbar/>
        
        {children}
        </body>
    </html>
  );
}
